# This is a basic workflow to help you get started with Actions

name: development_amplifydeployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test" ]
    
  repository_dispatch:
    types: development_amplifydeployment

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  qabuild:
    deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Webhook
  uses: joelwmale/webhook-action@master
  with:
    url: ${{ secrets.WEBHOOK_URL }}
    headers: '{"Content-Type": "application/json"}'
    body: '{}'