# This is a basic workflow to help you get started with Actions

name: development_autodeployment

# Controls when the workflow will run

  repository_dispatch:
    types: development_autodeployment

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  qabuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        run:      
            git checkout development
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build --if-present
        env:
          FIREBASE_SERVICE_ACCOUNT_DETAILS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  
      - name: npm run export
        run: npm run export        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:heartfulnesstestingapp     
        env:        
          PROJECT_ID: rameshtest-f25de
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
